### ISSUE TITLE
networkClient.init() error #1

### ISSUE THREAD

**Issue by fuguefoundation** [fuguefoundation/ng-colony#1]
See [app.component.ts](https://github.com/fuguefoundation/ng-colony/blob/master/src/app/app.component.ts)

`await networkClient.init();`

Error: No such event "UserLabelRegistered" on this contract
    at new ContractEvent (ContractEvent.js:47)

```
ColonyNetworkClient:
    events:
        AuctionCreated: ContractEvent {eventName: "AuctionCreated", client: ColonyNetworkClient, argsDef: Array(3), _wrappedHandlers: Map(0), assertValid: ƒ}
        ColonyAdded: ContractEvent {eventName: "ColonyAdded", client: ColonyNetworkClient, argsDef: Array(2), _wrappedHandlers: Map(0), assertValid: ƒ}
        SkillAdded: ContractEvent {eventName: "SkillAdded", client: ColonyNetworkClient, argsDef: Array(2), _wrappedHandlers: Map(0), assertValid: ƒ}
```

I found `UserLabelRegistered` as an event in `ColonyNetworkENS.sol`, not clear on its role within the ColonyNetworkClient object. Commenting out the following line allowed me to push forward to the second error.

./node_modules/@colony/colony-js-contract-client/lib/classes/ContractEvent.js

`47:    if (!this.interface) throw new Error('No such event "' + eventName + '" on this contract');`
